Athena/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from Promachos import views as views
from Promachos import APImobile as mobile

WebUrlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.login),
    url(r'^home$', views.home),
    url(r'^login/$', views.login),
    url(r'^aluno/$', views.aluno),
    url(r'^logout/$', views.logout),
    url(r'^perfil/$', views.perfil),
    url(r'^professor/$', views.professor),
    url(r'^cadastro/$', views.register_user),
    url(r'^aluno/aluno_turmas/$', views.aluno_turmas),
    url(r'^prof_ativ/(?P<id_ativ>[0-9]+)/$', views.prof_ativ),
    url(r'^aluno/aluno_ativ/(?P<ativ_id>[0-9]+)/$', views.aluno_ativ),
]

MobileUrlpatterns = [
    url(r'^Mlogin/$', mobile.login),
    url(r'^Matividades/$', mobile.atividades),
    url(r'^Mnotas/$', mobile.notas),
    url(r'^Mcalendario/$', mobile.calendario),
]

urlpatterns = WebUrlpatterns + MobileUrlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Athena/models.py
# -*- coding: utf-8 -*-
import os

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django_dropbox.storage import DropboxStorage


STORAGE = DropboxStorage()


def atividade_path(instance, filename):
    return 'atividades/{prof}/{turma}/{id}/{name}'.format(
        prof=instance.turma.professor.id,
        turma=instance.turma.id,
        id=instance.nome,
        name=filename,
    )


def turma_path(instance, filename):
    return 'atividades/{prof}/{turma}/{name}'.format(
        prof=instance.professor.id,
        turma=instance.id,
        name=filename,
    )


def submissao_path(instance, filename):
    return 'codigos/{aluno}/{atividade}/{name}'.format(
        aluno=instance.aluno.id,
        atividade=instance.atividade.id,
        name=filename,
    )


def zip_path(instance):
    return 'temp/{name}.zip'.format(
        name=instance.nome
    )


class Aluno(models.Model):

    Id = models.CharField(max_length=50, help_text="Id do Aluno")
    nome = models.CharField(max_length=50, help_text="Nome do Aluno")
    user = models.ForeignKey(
        User,
        help_text="Usuário de login relacionado ao Aluno",
    )

    def __str__(self):
        return '%s' % (self.nome.encode('utf-8'))

    def json_data(self):
        data = {}
        data['nome'] = self.nome
        data['username'] = self.user.get_username()
        data['email'] = self.user.email
        data['class'] = type(self).__name__
        return data


class Professor(models.Model):

    Id = models.CharField(max_length=50, help_text="Id do Professor")
    nome = models.CharField(max_length=50, help_text="Nome do Professor")
    user = models.ForeignKey(
        User,
        help_text="Usuário de login relacionado ao Professor",
    )

    def __str__(self):
        return '%s' % (self.nome.encode('utf-8'))

    def json_data(self):
        data = {}
        data['nome'] = self.nome
        data['username'] = self.user.get_username()
        data['email'] = self.user.email
        data['class'] = type(self).__name__
        return data


class Turma(models.Model):

    Id = models.CharField(max_length=50, help_text="Id da Turma")
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=2000)
    professor = models.ForeignKey(Professor, help_text="Professor da Turma")
    alunos = models.ManyToManyField(
        Aluno, help_text="Alunos inscritos na turma", blank=True,
    )

    def path(self, name):
        return turma_path(self, name)

    def __str__(self):
        return '%s %s' % (
            self.nome.encode('utf-8'),
            self.professor.nome.encode('utf-8')
        )


class Atividade(models.Model):

    def estaFechada(self):
        return self.data_limite < timezone.now().date()

    def path(self, name):
        return atividade_path(self, name)

    @property
    def submissoes(self):
        counterSubmissoes = 0
        for relAlunoAtividade in RelAlunoAtividade.objects.filter(
                atividade=self):
            if relAlunoAtividade.foiEntregue:
                counterSubmissoes = counterSubmissoes + 1
        return counterSubmissoes

    def prof_json_data(self):
        data = {}
        data['id'] = self.Id
        data['nome'] = self.nome
        data['professor'] = self.turma.professor.nome
        data['prazo'] = self.data_limite
        data['submissoes'] = self.submissoes

        return data

    Id = models.CharField(
        max_length=50, help_text="Id da Submissao"
    )
    nome = models.CharField(
        max_length=50
    )
    descricao = models.CharField(
        max_length=1000,
    )
    restricoes = models.CharField(
        max_length=1000,
    )
    arquivo_roteiro = models.FileField(
        upload_to=atividade_path, storage=STORAGE, null=True, default=None
    )
    arquivo_testador = models.FileField(
        upload_to=atividade_path, storage=STORAGE, null=True, default=None
    )
    arquivo_entrada = models.FileField(
        upload_to=atividade_path, storage=STORAGE, null=True, default=None
    )
    arquivo_entrada2 = models.FileField(
        upload_to=atividade_path, storage=STORAGE, null=True, default=None
    )
    arquivo_saida = models.FileField(
        upload_to=atividade_path, storage=STORAGE, null=True, default=None
    )
    arquivo_saida2 = models.FileField(
        upload_to=atividade_path, storage=STORAGE, null=True, default=None
    )

    # Armazenamento local de arquivos
    # arquivo_roteiro = models.FileField(
    #     upload_to=atividade_path, default=None
    # )
    # arquivo_testador = models.FileField(
    #     upload_to=atividade_path, default=None
    # )
    # arquivo_entrada = models.FileField(
    #     upload_to=atividade_path
    # )
    # arquivo_entrada2 = models.FileField(
    #     upload_to=atividade_path, default=None
    # )
    # arquivo_saida = models.FileField(
    #     upload_to=atividade_path
    # )
    # arquivo_saida2 = models.FileField(
    #     upload_to=atividade_path, default=None
    # )
    # def remove_file(self, filename):
    #     file = os.path.join(settings.MEDIA_ROOT,filename)
    #     if os.path.exists(file):
    #         os.remove(file)

    # def remove_roteiro(self, *args, **kwargs):
    #     self.remove_file(self.arquivo_roteiro.name)

    # def remove_testador(self, *args, **kwargs):
    #     self.remove_file(self.arquivo_testador.name)

    # def remove_entrada(self, *args, **kwargs):
    #     self.remove_file(self.arquivo_entrada.name)

    # def remove_entrada2(self, *args, **kwargs):
    #     self.remove_file(self.arquivo_entrada2.name)

    # def remove_saida(self, *args, **kwargs):
    #     self.remove_file(self.arquivo_saida.name)

    # def remove_saida2(self, *args, **kwargs):
    #     self.remove_file(self.arquivo_saida2.name)

    peso1 = models.IntegerField(default=1)
    peso2 = models.IntegerField(default=1)

    teste_publico = models.BooleanField(default=False)
    teste_privado = models.BooleanField(default=False)
    teste_customizado = models.BooleanField(default=False)

    data_limite = models.DateField()
    turma = models.ForeignKey(
        Turma,
        help_text="Turma a qual a atividade pertence",
    )
    alunos = models.ManyToManyField(
        Aluno,
        through='RelAlunoAtividade',
        help_text="""Relacao do aluno com a atividade,
            guarda se aluno submeteu atividade""",
        blank=True,
    )

    def __str__(self):
        return '%s %s' % (
            self.nome.encode('utf-8'), self.turma.nome.encode('utf-8'))

    def zip_path(self):
        return zip_path(self)

    def nome_roteiro(self):
        return os.path.basename(self.arquivo_roteiro.name)

    def nome_testador(self):
        return os.path.basename(self.arquivo_testador.name)

    def nome_entrada(self):
        return os.path.basename(self.arquivo_entrada.name)

    def nome_entrada2(self):
        return os.path.basename(self.arquivo_entrada2.name)

    def nome_saida(self):
        return os.path.basename(self.arquivo_saida.name)

    def nome_saida2(self):
        return os.path.basename(self.arquivo_saida2.name)

    def remove_roteiro(self, *args, **kwargs):
        STORAGE.delete(self.arquivo_roteiro.name)

    def remove_testador(self, *args, **kwargs):
        STORAGE.delete(self.arquivo_testador.name)

    def remove_entrada(self, *args, **kwargs):
        STORAGE.delete(self.arquivo_entrada.name)

    def remove_entrada2(self, *args, **kwargs):
        STORAGE.delete(self.arquivo_entrada2.name)

    def remove_saida(self, *args, **kwargs):
        STORAGE.delete(self.arquivo_saida.name)

    def remove_saida2(self, *args, **kwargs):
        STORAGE.delete(self.arquivo_saida2.name)


class Submissao(models.Model):

    RESULTADOS = (
        ('AC', 'Resposta correta'),
        ('AC2', 'Teste do professor executado com sucesso'),
        ('TLE', 'Tempo Limite Excedido'),
        ('RTE', 'Erro em tempo de execução'),
        ('CE', 'Erro de compilação'),
        ('WA', 'Erro no teste público'),
        ('WA2', 'Erro no teste privado'),
        ('INV', 'Código Inválido'),
        ('NE', 'Não entregue'),
    )

    statusDict = {
        "CE": "Erro de compilação",
        "WA": "Erro no teste público",
        "WA2": "Erro no teste privado",
        "INV": "Código inválido",
        "RTE": "Erro em tempo de execução",
        "TLE": "Tempo limite excedido",
        "AC": "Resposta correta",
        "AC2": "Teste do professor executado com sucesso",
        "NE": "Não entregue"
    }

    def path(self, name):
        return submissao_path(self, name)

    data_envio = models.DateField(
        auto_now=True,
        help_text='Data de submissão do código',
    )
    arquivo_codigo = models.FileField(
        upload_to=submissao_path, storage=STORAGE, null=True, default=None
    )

    # arquivo_codigo = models.FileField(upload_to=submissao_path)
    # def remove_file(self, *args, **kwargs):
    #     file = os.path.join(
    #         settings.MEDIA_ROOT,
    #         self.arquivo_codigo.name)
    #     if os.path.exists(file):
    #         os.remove(file)

    resultado = models.CharField(
        max_length=3,
        choices=RESULTADOS,
        help_text='Resultado da submissao do aluno',
    )
    nota = models.PositiveSmallIntegerField(
        help_text='Nota para submissão do aluno'
    )
    atividade = models.ForeignKey(
        Atividade,
        help_text="Atividade relacionada a submissão"
    )
    aluno = models.ForeignKey(
        Aluno,
        help_text="Aluno que enviou a submissão")

    def nome_codigo(self):
        return os.path.basename(self.arquivo_codigo.name)

    def remove_file(self, *args, **kwargs):
        STORAGE.delete(self.arquivo_codigo.name)

    def __str__(self):
        return '%s %s' % (
            self.atividade.nome.encode('utf-8'),
            self.aluno.nome.encode('utf-8')
        )


class RelAlunoAtividade(models.Model):

Promachos/models.py
# from django.db import models

# Create your models here.

Promachos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from Athena.models import Turma, Atividade


class UploadFileForm(forms.Form):

    file = forms.FileField()


class TurmaCreationForm(ModelForm):

    class Meta:
        model = Turma
        fields = ['nome', 'descricao']
        labels = {
            'nome': u'Nome da turma',
            'descricao': u'Descrição',
        }
        widgets = {
            'nome': forms.TextInput(attrs={
                'placeholder': 'Ex.: CES-10',
                'required': 'True',
                'class': 'form-group',
            }),
            'descricao': forms.Textarea(attrs={
                'placeholder': 'Ex.: Turma de CES-10 ministrada por João',
                'required': 'False',
                'rows': '5',
                'class': 'form-group',
            }),
        }


class AtividadeCreationForm(ModelForm):

    class Meta:
        model = Atividade
        fields = [
            'nome', 'descricao', 'data_limite', 'arquivo_roteiro'
        ]
        labels = {
            'nome': u'Nome da atividade*',
            'descricao': u'Descricao da atividade*',
            'data_limite': u'Data limite de entrega*',
            'arquivo_roteiro': u'Arquivo com roteiro*',
        }
        widgets = {
            'nome': forms.TextInput(attrs={
                'placeholder': 'Ex.: Lab 1-Printf',
                'required': 'True',
            }),
            'data_limite': forms.TextInput(attrs={
                'class': 'date_picker',
                'required': 'True',
            }),
            'descricao': forms.Textarea(attrs={
                'placeholder': 'Ex.: Lab que ensina a fazer printf',
                'required': 'True',
                'rows': '5',
            }),
            'arquivo_roteiro': forms.FileInput(attrs={
                'required': 'True',
            })
        }


class AtividadeEditForm(ModelForm):

    class Meta:
        model = Atividade
        fields = [
            'nome', 'descricao', 'data_limite', 'arquivo_roteiro'
        ]
        labels = {
            'nome': u'Nome da atividade',
            'descricao': u'Descricao da atividade',
            'data_limite': u'Data limite de entrega',
            'arquivo_roteiro': u'Novo arquivo com o roteiro (opcional)',
        }
        widgets = {
            'nome': forms.TextInput(attrs={
                'placeholder': 'Ex.: Lab 1-Printf',
            }),
            'descricao': forms.Textarea(attrs={
                'placeholder': 'Ex.: Lab que ensina a fazer printf',
                'rows': '5',
            }),
            'data_limite': forms.DateInput(attrs={
                'class': 'date_picker',
            }),
            'arquivo_roteiro': forms.FileInput(attrs={
            })
        }

Promachos/templates/aluno.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Athena | Aluno</title>
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <style type="text/css">
    .bs-example{
        margin: 20px;
    }

    * {margin: 0; padding: 0;}

    div.list {
      margin: 20px;
    }

    ul {
      list-style-type: none;
      width: 500px;
    }

    ul a {
      color: #000;
    }

    ul a:hover {
      color: #000;
      text-decoration: none;
    }

    h3 {
      font: bold Helvetica, Verdana, sans-serif;
    }

    li img {
      float: left;
      margin: 15px 15px 0 0;
    }

    li p {
      font: 200 12px/1.5 Georgia, Times New Roman, serif;
    }

    li.list {
      padding: 0 0 10px 0;
      overflow: auto;
    }

    li.list:hover {
      background: #d7e0f9;
      cursor: pointer;
    }

    .thumbnail_work {
      height: 310px;
      text-align: center;
    }

    .tab-pane {
      padding-top: 20px;
    }

    .detalhes {
      text-align: center;
    }
  </style>
</head>

<body>
<!-- Redireciona aluno para Tab da nova turma -->
{% if nova_turma %}
  <script>
  $( document ).ready(function() {
    $("[href=\"#{{nova_turma.id}}\"]").tab('show');
  });
  </script>
{% endif %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      <img src="/static/img/ita_logo.jpg" style="height: 75px;">
    </div>
    <div class="col-sm-6">
      <h2 align="center">Olá {{aluno.user}}</h2>
      <h4 align="center">{{aluno.user.email}}</h4>
    </div>
    <div class="col-sm-3" style="text-align: right;">
      <p style="line-height: 40px;"><a href="/logout/" class="btn btn-danger" role="button"><span class="glyphicon glyphicon-off"></span> Sair</a></p>
    </div>
  </div>
  <div class="row" style="padding-top: 15px;">
    <div class="col-xs-12">
      <div role="tabpanel">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" style="width: 100%;">
          <li role="presentation" class="active">
            <a href="#workspace" aria-controls="workspace" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-home"></span> Workspace</a>
          </li>
		  {% for turma in turmas %}
          <li role="presentation">
            <a href=#{{turma.id}} aria-controls={{turma.id}}  role="tab" data-toggle="tab">{{turma.nome}}</a>
          </li>
		  {% endfor %}
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane fade in active" id="workspace">
            <div class="row">
              <div class="col-xs-12 col-sm-3" style="margin-top: 130px;">
                <a href="aluno_turmas" class="btn btn-lg btn-block btn-default">Ver turmas disponíveis</a><br>
              </div>

              <div class="col-xs-12 col-sm-5">
                <div class="thumbnail thumbnail_work">
                  <div class="caption">
                  <p><h3>Últimas submissões</h3></p>
                  <br>
                  {% for nome_ativ,data,nome_turma in ultimas_submissoes %}
                  <p><font color="green">{{nome_ativ}}</font> - Turma: <font color="green">{{nome_turma}}</font> - Último envio em: {{data}}</p>
                  {% endfor %}
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-sm-4">
                <div class="thumbnail thumbnail_work">
                  <div class="caption">
                  <h3>Atividades pendentes</h3>
                  <br>
                  {% for data,turma,nome in atividades_pendentes %}
                  <p>{{data}} - <font color="green">{{turma.nome}}</font> > <font color="green">{{nome}}</font></p>
                  {% endfor %}
                  <br>
                  </div>
                </div>
              </div>
            </div> <!-- end of row -->
          </div> <!-- end of workspace tab -->
          {% for pane in panes %}
              {{pane |safe}}
          {% endfor %}          
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

Promachos/templates/aluno_ativ.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Athena | Atividade</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/athena.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div id="loading" style="display:none;">
      <div id="loader"></div>
      <h2 id="loader_message">Aguarde, carregando...</h2>
    </div>
    <div id="content" class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <img src="/static/img/ita_logo.jpg" style="height: 75px;">
      </div>
      <div class="col-sm-6">
        <h2 align="center">Olá {{aluno.user}}</h2>
        <h4 align="center">{{aluno.user.email}}</h4>
      </div>
      <div class="col-xs-3" style="text-align: right;">
        <p style="line-height: 40px;"><a href="/aluno/" class="btn btn-default" role="button"><span class="glyphicon glyphicon-home"></span> Workspace</a> | <a href="/logout" class="btn btn-danger" role="button"><span class="glyphicon glyphicon-off"></span> Sair</a></p>
      </div>
    </div>
    <div class="row" style="padding-top: 15px;">
    <div class="col-xs-12">
      <div role="tabpanel">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" style="width: 100%;">
          <li role="presentation" class="active">
            <a href="#atividade" aria-controls="atividade" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-file"></span> Atividade</a>
          </li>
          <li role="presentation">
            <a href="#workspace" aria-controls="workspace" role="tab" data-toggle="tab" onclick="location.href='/aluno/';"><span class="glyphicon glyphicon-home"></span> Workspace</a>
          </li>
          {% for turma in turmas %}
          <li role="presentation">
            <a href=#{{turma.id}} aria-controls={{turma.id}}  role="tab" data-toggle="tab" onclick="location.href='/aluno/';">{{turma.nome}}</a>
          </li>
          {% endfor %}
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane fade in active" id="workspace">
            <div align="center">
        <p><h2> {{ atividade.nome }} </h2></p>
              <p><h4>{{atividade.turma.nome}} - Prof. {{atividade.turma.professor.nome}} </h4></p>
              {% if atividade.estaFechada %}
              <h4 style="color:red">Atividade fechada (em {{atividade.data_limite}})</h4>
              {% else %}
              <h4 style="color:green">Atividade aberta (até {{atividade.data_limite}})</h4>
              {% endif %}
              {% if atividade.teste_publico or atividade.teste_privado or atividade.teste_customizado %}
                <h5>
                Incluindo testes
                {% if atividade.teste_publico %}
                  Públicos
                {% endif %}
                {% if atividade.teste_privado %}
                  Privados
                {% endif %}
                {% if atividade.teste_customizado %}
                  Customizados
                {% endif %}
                </h5>
              {% endif %}
            </div>
            <div class="row">
              <div class="col-xs-12 col-sm-4">
                <div class="thumbnail thumbnail_work">
                  <div class="caption">
                    <div class="form-group">
                      <h4 align="center"><b>Submissão:</b></h4>
                      <hr>
                      <p><b>Descrição: </b>{{ atividade.descricao }}</p>
                      <p><b>Atividade:</b> 
                        {% if atividade.arquivo_roteiro and atividade.arquivo_roteiro.url %}
                          <a href="{{ atividade.arquivo_roteiro.url }}" target="_blank">{{ atividade.nome_roteiro }}</a>
                        {% else %}
                        Não há
                        {% endif %}
                      </p>

                      {% if atividade.teste_publico%}
                      <p><b>Entrada pública:</b> 
                        {% if atividade.arquivo_entrada and atividade.arquivo_entrada.url%}
                          <a href="{{ atividade.arquivo_entrada.url }}" target="_blank">{{ atividade.nome_entrada }}</a>
                        {% else %}
                        Não há
                        {% endif %}
                      </p>
                      {% endif %}

                      {% if not atividade.teste_customizado and atividade.arquivo_saida.url%}
                      <p><b>Saída pública:</b> 
                        {% if atividade.arquivo_saida %}
                          <a href="{{ atividade.arquivo_saida.url }}" target="_blank">{{ atividade.nome_saida }}</a>
                        {% else %}
                        Não há
                        {% endif %}
                      </p>
                      {% endif %}

                      <p><b>Restrições: </b>{{atividade.restricoes}}</p>
                      </p>
                    </div>
                    {% if prazo_valido %}
                    <form method="POST" enctype="multipart/form-data" id="post_submissao">
                      {% csrf_token %}
                      <div class="form-group" align="center">
                        <a id="compilador" data-content="Comando de compilação usado: g++ programa.c -g -pthread -pg -std=c++0x -o programa.out" rel="popover" data-placement="top" data-original-title="Compilador usado: g++" data-trigger="hover"><b>Código da solução (.c ou .cpp):</b></a>
                        <script>
                          $("#compilador").popover();
                        </script>
                        <input id="id_arquivo_codigo" name="arquivo_codigo" required="True" type="file">
                      </div>
                      <div class="form-group" align="center">
                        <button class="btn btn-primary" type="submit" value="Submit"><span class="glyphicon glyphicon-open"></span> Enviar solução</button>
                        <script>
                          $("#post_submissao").bind('submit', function() {
                            $("#loading").css("display", "block");
                            $("#content").css({ opacity: 0.3 });
                          });
                        </script>
                      </div>
                    </form>
                    {% else %}
                    <p style="color:red"><b>Prazo vencido.</b></p>
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="col-xs-12 col-sm-3">
                <div class="thumbnail thumbnail_work">
                  <div class="caption" >
                    <h4 align="center"><b>Status de Submissão:</b></h4>
                    <hr>
                    {% if submissao and relAlunoAtividade %}
                    {% if relAlunoAtividade.foiEntregue %}
                    <div class="form-group">
                      <p><b>Última submissão:</b> 
                        {% if submissao.arquivo_codigo and submissao.arquivo_codigo.url%}
                        <a href="{{ submissao.arquivo_codigo.url }}" target="_blank">{{ submissao.nome_codigo }}</a>
                        {% else %}
                        Não há
                        {% endif %}
                      </p>
                      <p><b>Status:</b> {{status}}</p>
                      <p><b >Nota:</b> {{ submissao.nota }}</p>
                      <p><b>Data limite:</b> {{ atividade.data_limite }}</p>
                      <p><b>Último envio:</b> {{ submissao.data_envio }}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs-12 col-sm-5">
                <div class="thumbnail thumbnail_work">
                  <div class="caption">
                    <div class="form-group">
                      <h4 align="center"><b>Arquivos de saída:</b></h4>
                      <hr>
                      <p style="color:red"> {{ compilation_error|safe }} </p>
                      <!-- TABELA COMECA AQUI!!! -->
                      <table class="table">
                        <tr>
                          <th>#</th>
                          <th>Saída do aluno</th>
                          <th>Saída do professor</th>
                        </tr>
                        {% for saida in lista_saida %}
                        <tr>
                          <td>{{forloop.counter}}</td>
                          {% if saida.0 %}
                          <td>{{saida.0}}</td>
                          {% else %}
                          <td></td>
                          {% endif %}
                          {% if saida.1 %}
                          <td>{{saida.1}}</td>
                          {% else %}
                          <td></td>
                          {% endif %}
                        </tr>
                        {% endfor %}
                      </table>
                      <!-- TABELA TERMINA AQUI!!! -->
                    </div>
                    {% else %}
                    <div class="form-group">
                      <p><b>Status:</b> Não entregue.</p>
                      <p><b>Nota:</b> -</p>
                      <p><b>Data limite:</b> {{ atividade.data_limite }}</p>
                      <p><b>Último envio:</b> -</p>
                    </div>
                    {% endif %}
                    {% else %}
                    <div class="form-group">
                      <p><b>Status:</b> Não entregue.</p>
                      <p><b>Nota:</b> -</p>
                      <p><b>Data limite:</b> {{ atividade.data_limite }}</p>
                      <p><b>Último envio:</b> -</p>
                    </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
            <!-- end of row -->
          </div>
          <!-- end of Workspace tab -->
        </div>
        <!-- end of tab content -->
      </div>
      <!-- end of tab pane -->
    </div>
    <!-- end of container -->
  </body>
</html>

Promachos/templates/logout.html
{% block content %}

  <h2>Logged out!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again</p>

{% endblock %}